# - name: o3-mini
#   edit_format: diff
#   weak_model_name: anthropic-3-5-sonnet
#   use_repo_map: true
#   use_temperature: false
#   editor_model_name: o3-mini 
#   editor_edit_format: editor-diff
#   extra_params:
#     extra_body:
#       reasoning_effort: high

# - name: o1-preview
#   edit_format: diff
#   use_repo_map: true
#   use_temperature: false
#   editor_model_name: o1-preview
#   editor_edit_format: editor-diff
#   extra_params:
#     extra_body:
#       reasoning_effort: high

