#!/bin/bash

# Script to prepare unused images for removal
# Total files: 47
# Total size: 19.39 MB
# Generated by scripts/find_unused_images.py

# Safety check
echo '⚠️  This script will prepare the following images for removal:'
echo ''
echo '  - 0 copy.png'
echo '  - Facebook Cover Image.png'
echo '  - Facebook Profile Image.png'
echo '  - Grayscale Transparent.png'
echo '  - Grayscale Transparent.svg'
echo '  - Original Logo Symbol.png'
echo '  - Original Logo.png'
echo '  - Original Logo.svg'
echo '  - Transparent Logo.png'
echo '  - Transparent Logo.svg'
echo '  - about_me_profile_1.jpeg'
echo '  - about_me_profile_3.jpeg'
echo '  - about_me_profile_4.jpeg'
echo '  - aitoai.png'
echo '  - akashic.png'
echo '  - chipbrain.webp'
echo '  - fingers.jpg'
echo '  - flowstate-card.png'
echo '  - greece_profile1.jpeg'
echo '  - handshake.jpg'
echo '  - hbi_transparent.webp'
echo '  - hdi_logo_v01-1.png'
echo '  - hdi_logo_v01-3.png'
echo '  - hdi_logo_v01-4.jpg'
echo '  - hdi_logo_v01-5.jpg'
echo '  - hdi_logo_v01-6.jpg'
echo '  - hdi_logo_v01-7.jpg'
echo '  - holodeck.jpg'
echo '  - inthehand.webp'
echo '  - logo_v1.jpeg'
echo '  - logo_v1.png'
echo '  - phoneagent.jpg'
echo '  - phonelock.webp'
echo '  - preflight-card.png'
echo '  - preflight-gpt-logo.png'
echo '  - preflight-gpt2.png'
echo '  - robosec.webp'
echo '  - saigo_1.webp'
echo '  - saigo_2.webp'
echo '  - saigo_3.webp'
echo '  - saigo_4.webp'
echo '  - siago_5.webp'
echo '  - single-multi.jpeg'
echo '  - solarlib.jpeg'
echo '  - spirit_book.png'
echo '  - unimon.webp'
echo '  - watson-gpt-logo.png'

echo ''
echo '📦 Creating backup directory...'
mkdir -p ./backup_images

echo '🔄 Moving images to backup directory...'

mv ./public/images/0 copy.png ./backup_images/0 copy.png
echo '  Moved: 0 copy.png'
mv ./public/images/Facebook Cover Image.png ./backup_images/Facebook Cover Image.png
echo '  Moved: Facebook Cover Image.png'
mv ./public/images/Facebook Profile Image.png ./backup_images/Facebook Profile Image.png
echo '  Moved: Facebook Profile Image.png'
mv ./public/images/Grayscale Transparent.png ./backup_images/Grayscale Transparent.png
echo '  Moved: Grayscale Transparent.png'
mv ./public/images/Grayscale Transparent.svg ./backup_images/Grayscale Transparent.svg
echo '  Moved: Grayscale Transparent.svg'
mv ./public/images/Original Logo Symbol.png ./backup_images/Original Logo Symbol.png
echo '  Moved: Original Logo Symbol.png'
mv ./public/images/Original Logo.png ./backup_images/Original Logo.png
echo '  Moved: Original Logo.png'
mv ./public/images/Original Logo.svg ./backup_images/Original Logo.svg
echo '  Moved: Original Logo.svg'
mv ./public/images/Transparent Logo.png ./backup_images/Transparent Logo.png
echo '  Moved: Transparent Logo.png'
mv ./public/images/Transparent Logo.svg ./backup_images/Transparent Logo.svg
echo '  Moved: Transparent Logo.svg'
mv ./public/images/about_me_profile_1.jpeg ./backup_images/about_me_profile_1.jpeg
echo '  Moved: about_me_profile_1.jpeg'
mv ./public/images/about_me_profile_3.jpeg ./backup_images/about_me_profile_3.jpeg
echo '  Moved: about_me_profile_3.jpeg'
mv ./public/images/about_me_profile_4.jpeg ./backup_images/about_me_profile_4.jpeg
echo '  Moved: about_me_profile_4.jpeg'
mv ./public/images/aitoai.png ./backup_images/aitoai.png
echo '  Moved: aitoai.png'
mv ./public/images/akashic.png ./backup_images/akashic.png
echo '  Moved: akashic.png'
mv ./public/images/chipbrain.webp ./backup_images/chipbrain.webp
echo '  Moved: chipbrain.webp'
mv ./public/images/fingers.jpg ./backup_images/fingers.jpg
echo '  Moved: fingers.jpg'
mv ./public/images/flowstate-card.png ./backup_images/flowstate-card.png
echo '  Moved: flowstate-card.png'
mv ./public/images/greece_profile1.jpeg ./backup_images/greece_profile1.jpeg
echo '  Moved: greece_profile1.jpeg'
mv ./public/images/handshake.jpg ./backup_images/handshake.jpg
echo '  Moved: handshake.jpg'
mv ./public/images/hbi_transparent.webp ./backup_images/hbi_transparent.webp
echo '  Moved: hbi_transparent.webp'
mv ./public/images/hdi_logo_v01-1.png ./backup_images/hdi_logo_v01-1.png
echo '  Moved: hdi_logo_v01-1.png'
mv ./public/images/hdi_logo_v01-3.png ./backup_images/hdi_logo_v01-3.png
echo '  Moved: hdi_logo_v01-3.png'
mv ./public/images/hdi_logo_v01-4.jpg ./backup_images/hdi_logo_v01-4.jpg
echo '  Moved: hdi_logo_v01-4.jpg'
mv ./public/images/hdi_logo_v01-5.jpg ./backup_images/hdi_logo_v01-5.jpg
echo '  Moved: hdi_logo_v01-5.jpg'
mv ./public/images/hdi_logo_v01-6.jpg ./backup_images/hdi_logo_v01-6.jpg
echo '  Moved: hdi_logo_v01-6.jpg'
mv ./public/images/hdi_logo_v01-7.jpg ./backup_images/hdi_logo_v01-7.jpg
echo '  Moved: hdi_logo_v01-7.jpg'
mv ./public/images/holodeck.jpg ./backup_images/holodeck.jpg
echo '  Moved: holodeck.jpg'
mv ./public/images/inthehand.webp ./backup_images/inthehand.webp
echo '  Moved: inthehand.webp'
mv ./public/images/logo_v1.jpeg ./backup_images/logo_v1.jpeg
echo '  Moved: logo_v1.jpeg'
mv ./public/images/logo_v1.png ./backup_images/logo_v1.png
echo '  Moved: logo_v1.png'
mv ./public/images/phoneagent.jpg ./backup_images/phoneagent.jpg
echo '  Moved: phoneagent.jpg'
mv ./public/images/phonelock.webp ./backup_images/phonelock.webp
echo '  Moved: phonelock.webp'
mv ./public/images/preflight-card.png ./backup_images/preflight-card.png
echo '  Moved: preflight-card.png'
mv ./public/images/preflight-gpt-logo.png ./backup_images/preflight-gpt-logo.png
echo '  Moved: preflight-gpt-logo.png'
mv ./public/images/preflight-gpt2.png ./backup_images/preflight-gpt2.png
echo '  Moved: preflight-gpt2.png'
mv ./public/images/robosec.webp ./backup_images/robosec.webp
echo '  Moved: robosec.webp'
mv ./public/images/saigo_1.webp ./backup_images/saigo_1.webp
echo '  Moved: saigo_1.webp'
mv ./public/images/saigo_2.webp ./backup_images/saigo_2.webp
echo '  Moved: saigo_2.webp'
mv ./public/images/saigo_3.webp ./backup_images/saigo_3.webp
echo '  Moved: saigo_3.webp'
mv ./public/images/saigo_4.webp ./backup_images/saigo_4.webp
echo '  Moved: saigo_4.webp'
mv ./public/images/siago_5.webp ./backup_images/siago_5.webp
echo '  Moved: siago_5.webp'
mv ./public/images/single-multi.jpeg ./backup_images/single-multi.jpeg
echo '  Moved: single-multi.jpeg'
mv ./public/images/solarlib.jpeg ./backup_images/solarlib.jpeg
echo '  Moved: solarlib.jpeg'
mv ./public/images/spirit_book.png ./backup_images/spirit_book.png
echo '  Moved: spirit_book.png'
mv ./public/images/unimon.webp ./backup_images/unimon.webp
echo '  Moved: unimon.webp'
mv ./public/images/watson-gpt-logo.png ./backup_images/watson-gpt-logo.png
echo '  Moved: watson-gpt-logo.png'

echo ''
echo '✅ Images moved to ./backup_images/'
echo ''
echo 'To restore images, run:'
echo '  mv ./backup_images/* ./public/images/'
echo ''
echo 'To permanently delete backed up images, run:'
echo '  rm -rf ./backup_images'