-- SQLite
INSERT INTO Name (id, name, created_at)
VALUES (5, 'Human Dissent Interface'),
    (6, 'Higher Dimensions Institute'),
    (7, 'Hyper Divergence Initiative'),
    (8, 'Hacker Development Initiative'),
    (9, 'Hyper Dream Interpretation'),
    (10, 'Human Divinity Interface'),
    (11, 'Havoc Design Initiative'),
    (12, 'Holistic Discovery Institute'),
    (13, 'Hyperconscious Design Institute'),
    (14, 'Higher Dimensional Intelligence'),
    (15, 'Hacker Dynamics Incorporated'),
    (16, 'Heart Data Incorporated'),
    (17, 'Higher Destiny Interface'),
    (18, 'Healing Dimensions Institute'),
    (19, 'Harmonic Dawn Initiative'),
    (20, 'Holistic Divergence Institute'),
    (21, 'Human Discovery Interface'),
    (22, 'Hyperconscious Design Innovators'),
    (23, 'Higher Destiny Integration'),
    (24, 'Hyperlink Database Integrators'),
    (25, 'Human Dynamics Integration'),
    (26, 'Holistic Data Interface'),
    (27, 'Hyperlink Destiny Initiative'),
    (28, 'Hyper Disruptive Interface'),
    (29, 'Human Defiance Initiative'),
    (30, 'Heretic Development Interface'),
    (31, 'Human Dissent Interface');
