-- Create AB testing tracking table
CREATE TABLE IF NOT EXISTS ab_test_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id TEXT NOT NULL,
  variant TEXT NOT NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  user_agent TEXT,
  ip_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Add indexes for queries we'll need for reporting
  CONSTRAINT ab_test_events_variant_check CHECK (variant IN ('A', 'B'))
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS ab_test_events_test_id_idx ON ab_test_events(test_id);
CREATE INDEX IF NOT EXISTS ab_test_events_variant_idx ON ab_test_events(variant);
CREATE INDEX IF NOT EXISTS ab_test_events_event_type_idx ON ab_test_events(event_type);

-- Create view for easy reporting
CREATE OR REPLACE VIEW ab_test_results AS
SELECT 
  test_id,
  variant,
  event_type,
  COUNT(*) as event_count,
  COUNT(DISTINCT ip_hash) as unique_visitors
FROM ab_test_events
GROUP BY test_id, variant, event_type; 